_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/idqn.py
        m: []
        python_version: 3.7.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.7.11
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
algo:
    value: idqn
batch_size:
    value: 32
buffer_limit:
    value: 50000
env_name:
    value: ma_gym:Switch2-v1
gamma:
    value: 0.99
log_interval:
    value: 20
lr:
    value: 0.0005
max_episodes:
    value: 30000
max_epsilon:
    value: 0.9
min_epsilon:
    value: 0.1
monitor:
    value: false
test_episodes:
    value: 5
update_iter:
    value: 10
warm_up_steps:
    value: 2000
